- name: Create Gophish group 
  group:
    name: gophish
    state: present

- name: Create Gophish user
  user:
    name: gophish
    uid: 1040
    group: gophish

- name: Install docker
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items: 
    - docker 
    - docker-compose
  
- name: Copy docker/gophish files
  copy:
    src: files/
    dest: /gophish
    owner: gophish
    group: gophish
    mode: 0644

- name: Generate Passwords
  set_fact:
    root_pass: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"
    gophish_pass: "{{ lookup('password', '/dev/null length=64 chars=ascii_letters,digits') }}"

- name: Register DB passwords
  shell: echo '{{item.value}}' >> /gophish/{{item.name}}
  loop:
    - {name: 'db_root_password',   value: '{{ root_pass }}'}
    - {name: 'db_gophish_password',value: '{{ gophish_pass }}'}

- name: Update Gophish Config 
  shell: sed -i 's/gophish_passwd/{{ gophish_pass }}/g' /gophish/config.json

- name: Create SSL Cert links
  shell: ln -s '/etc/letsencrypt/live/{{ domain }}/{{ item.value }}' /gophish/'{{ item.name }}'
  loop:
    - {name: 'gophish.crt', value: 'fullchain.pem'}
    - {name: 'gophish.key', value: 'privkey.pem'}

- name: Allow gophish to read crt/key
  shell: chmod +r /gophish/gophish.crt /gophish/gophish.key

- name: Docker compose up gophish
  docker_compose:
    project_src: /gophish
    state: present
    
- name: Get Ip of gophish container
  docker_container_info:
    name: gophish
  register: gophish_ip
  
- name: Show ip of gophish container
  debug:
    var: gophish_ip

- name: Update Postfix to talk to gophish
  shell: postconf inet_interfaces=172.17.0.1 mynetworks="{{ gophish_ip.container.NetworkSettings.Networks.gophish_default.IPAddress }}"

  
- name: Allow gophish ip to localhost
  shell: ufw allow in from "{{ gophish_ip.container.NetworkSettings.Networks.gophish_default.IPAddress }}"

- name: Reload Postfix
  ansible.builtin.service:
    name: postfix
    state: reloaded

- name: Get GoPhish API key
  community.docker.docker_container_exec:
    container: mysql
    command: /bin/sh -c 'mysql -u root -p{{ root_pass }} -B -N -e "use gophish; select api_key from users where username=\"admin\";"'
  register: api_key

- name: Copy over test email script
  ansible.builtin.template:
    src: templates/test_email.sh.j2
    dest: /gophish/test_email.sh
    mode: u=x,g=r,o=r

- name: Send Test email
  shell: bash /gophish/test_email.sh





